postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: postgres

redis:
  host: localhost
  port: 6379
  password:
  DB: 0

server:
  port: 8080
  host: 127.0.0.1

JWT:
  secret: asd

mailer:
  name: SAPR ROAD
  from_email_address: vpbuyanovv@gmail.com
  from_email_password: umpuwkthejjgvssf