version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      gw-backend:

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    env_file:
      - .redis.env
    volumes:
      - redis-data:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      gw-backend:

  gw-backend-go:
    image: vpbuyanov/gw-backend-go:latest
    container_name: gw-backend-go
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      gw-backend:

volumes:
  redis-data:
  postgres-data:

networks:
  gw-backend: