name: Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.6

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: go mod download

      - name: Install Lint
        run: sudo snap install golangci-lint

      - name: Lint
        run: golangci-lint run

