name: Check
on:
  push:
    branches:
      - main
      - ci
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: go mod download
      - name: Lint
        run: golangci-lint run

