name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --out-format colored-line-number
        continue-on-error: true

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up go Environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          go mod tidy

      - name: Run Tests
        run: |
          go test ./...

  build_and_push:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test

    steps:
      - name: Build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/gw-backend-go:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/gw-backend-go:latest
          push: true

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build_and_push

    steps:
      - name: Get new image and replace container
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          script: |
            cd gw-devops
            
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            
            docker stop backend
            
            docker rm backend
            
            docker rmi -f $(docker images -aq)
            
            docker compose up -d
