name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.21.6

    steps:
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: go mod download

      - name: Install Lint
        run: sudo snap install golangci-lint

      - name: Lint
        run: golangci-lint run

  build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        go-version:
        - 1.21.6

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...
